server:
  port: 9090
  servlet:
    context-path: /api
spring:
  mvc:
    date-format: yyyy-MM-dd
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  application:
    name: new_committee
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: Retail_HikariCP
      minimum-idle: 5 #最小空闲连接数量
      idle-timeout: 180000 #空闲连接存活最大时间，默认600000（10分钟）
      maximum-pool-size: 10 #连接池最大连接数，默认是10
      auto-commit: true  #此属性控制从池返回的连接的默认自动提交行为,默认值：true
      max-lifetime: 1800000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      connection-timeout: 30000 #数据库连接超时时间,默认30秒，即30000
      connection-test-query: SELECT 1
  profiles:
    active: prod

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
version: 10.6.19

huawei:
  sms:
    url: https://rtcsms.cn-north-1.myhuaweicloud.com:10743/sms/batchSendSms/v1  # APP接入地址+接口访问URI
    appKey: Aeio4815PHanS65ZEMwbqvKzFmFZ  # APP_Key
    appSecret: 9CrX2m6yjJOF45x14EzHwTvtidQf  # APP_Secret
    sender: 8821041208745  # 国内短信签名通道号或国际/港澳台短信通道号
    templateId: ca1d293f12ef4a65b078e4adba703869   # 模板ID
    signature: 微学工  # 签名名称

swagger:
  enabled: false
