spring:
  datasource:
#    url: jdbc:mysql://kddgw-test.wjy2000.cn:3306/new-committee?serverTimezone=Asia/Shanghai

#    演示数据
#    url: jdbc:mysql://localhost:3306/kddgw_fake?serverTimezone=Asia/Shanghai

    url: jdbc:mysql://localhost:3306/new-committee?serverTimezone=Asia/Shanghai
    username: root
#    username: nplus_remote
#    password: 2021@nplus
    password: mysql666
  redis:
#    host: 49.233.32.252
    host: 127.0.0.1
    port: 6379
#    password: gaoyuan
filepath: /photos
tFilePath: /photos/admin/
defaultPhoto: default.jpg
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl