spring:
  datasource:
    url: jdbc:mysql://xg-meeting.wjy2000.cn:3306/new-committee?serverTimezone=Asia/Shanghai
#    url: jdbc:mysql://localhost:3306/new-committee?serverTimezone=Asia/Shanghai
#    username: root
#    password: CUMTdzsw2016
    username: nplus_remote
    password: nplus666
  #    password: 123456
  redis:
#    host: 49.233.32.252
    host: 127.0.0.1
    port: 6379
#    password: gaoyuan
filepath: /photos
defaultPhoto: default.jpg
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl