spring:
  datasource:
    url: jdbc:mysql://mysql:3306/new-committee?serverTimezone=Asia/Shanghai
    username: root
    password: xxxxxx
  redis:
    host: redis
    password: xxxxxx
filepath: /photos
defaultPhoto: default.jpg