spring:
  datasource:
    url: jdbc:mysql://mysql:3306/new-committee?serverTimezone=Asia/Shanghai
    username: root
    password: nplus666
  redis:
    host: redis
    password: gaoyuan
filepath: /photos
tFilePath: /photos/admin/
defaultPhoto: default.jpg