spring:
  datasource:
    url: jdbc:mysql://kddgw-test.wjy2000.cn:3306/new-committee?serverTimezone=Asia/Shanghai
    username: nplus_remote
    password: 2021@nplus
  redis:
    host: kddgw-test.wjy2000.cn
    password: kddgw_test_redis
filepath: /photos
tFilePath: /photos/admin/
defaultPhoto: default.jpg
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl